### ISSUE TITLE
convert Json files to CSV

### ISSUE THREAD

**Issue by andreawaxman** [vangul01/BDSProject#1]
Yelp data needs to be converted.

**Comment by nspektor** [comment]
Run instructions:

```$ python3 json_to_csv.py big_yelp_data/business.json```

note: this is assuming you have business.json in a folder titled big_yelp_data in your current directory
this is how I have it and it is not pushed to github thanks to .gitignore, so if you have it in a different directory, 
edit` .gitignore` accordingly
