### ISSUE TITLE
IDEA: look at all non-green restaurants and if they contain manually generated "green" words -> give them a green rating of 1

### ISSUE THREAD

**Issue by andreawaxman** [vangul01/BDSProject#2]
Word count. Use rapid miner to analyze data quickly, make sure we have enough reviews for our use.

**Comment by vangul01** [comment]
1. filter out the restaurants from NYC (or NY, nyc may be spelled weird and well have to check for that) in businesses csv
  - make python dictionary for words that description has to contain (food, restaurants, cafe, bars, others...)
2. uniform the data in yelp to attempt matching restaurant names with any names in green rating file
3. MATCH ON NAME! :D 
4. turn yelp reviews data into csv, match restaurants with their reviews
5. attempt to match reviews, restaurants, POSSIBLY greenrating data
