### ISSUE TITLE
Figure out which features to control for

### ISSUE THREAD

**Issue by nspektor** [vangul01/BDSProject#3]
- ask cole
- read past articles to figure out what features are important

Example:
- restaurants with good air quality do better so only look at restaurants with good air quality
- a restaurant in ny is 50% more likely to close than one in nj
...

**Comment by andreawaxman** [comment]
Articles:
https://cdn2.hubspot.net/hubfs/412971/Content_+_Assets/2018%20Restaurant%20Success%20Industry%20Report.pdf

https://www.theinfatuation.com/new-york/guides/best-new-new-york-restaurants-hit-list

Specialty, price, drinks, service, use of technology (like text messages for notifying customers when table is ready)

**Comment by andreawaxman** [comment]
Control to cross validate the features for the data will be a sample of the data we use. The 'testing' data that we will use as the control or the reference will stay constant as we compare it with the rest of the data.

Features should include: 

- restaurant location setting (surroundings, neighborhood, rat calls frequency)
- positive yelp reviews
- green rating (from GRA = green restaurant association)
- quality of customer service / service / technology used (ie. sms to notify customers about the status of their table)
