### ISSUE TITLE
Define restaurant success

### ISSUE THREAD

**Issue by nspektor** [vangul01/BDSProject#4]
- how long its been open
- how many locations it has
- yelp rating

**Comment by andreawaxman** [comment]
- Does the restaurant offer a unique experience, (ie. unique food, unique presentation of food, unique decorations, unique music, etc)
- Does the restaurant generate traffic during slow times? Perhaps by offering special promotions during off-peak times.
- Does the restaurant receive good ratings & positive reviews? (Yelp 'highly recommended')
- Is the restaurant clean? (inspection grade, rat calls in area, yelp reviews about clean/dirty)
- Does the restaurant offer quality food? (Yelp reviews, check to mention 'quality', 'hair in food', 'plastic', 'fresh', 'organic', 'smell')
- Does the restaurant have multiple locations? Has it expanded? How many customers does it have? (can give us insight to how much money it has to pay its employees)
